stages:
  - build

Ubuntu-subproject:
  stage: build
  script:
  - export BUILD_GENERATOR="Ninja"
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - bash .gitlab-ci.sh
  tags:
  - ubuntu


OSX-subproject:
  stage: build
  script:
  - export BUILD_GENERATOR="Ninja"
  - module load Qt-5.9.1
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DCMAKE_FRAMEWORK_PATH=$QGLVIEWER_ROOT/usr/local/lib -DSOIL_ROOT_DIR=$SOIL_ROOT_DIR"
  - bash .gitlab-ci.sh
  tags:
  - osx-sierra

Win7-VS14-x64-subproject:
  stage: build
  script:
  - call %ENVFILESDIR%\Qt-5.12-vs14.bat
  - call %ENVFILESDIR%\Boost-1.71-vs14-x64.bat
  - set PATH=%PATH%;"c:\Program Files\Git\bin"
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - bash --login .gitlab-ci.sh
  tags:
  - win7
  except:
  - tags
